events {
    worker_connections 1024;
}

http {
    upstream aspnet_app {
        server aspnet_app:85;
    }

    server {
        listen 80;
        # listen 443 ssl; # если нужен HTTPS
        # ssl_certificate /etc/nginx/ssl/your_cert.crt;
        # ssl_certificate_key /etc/nginx/ssl/your_key.key;

        location / {
            proxy_pass http://aspnet_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Дополнительные настройки для MinIO и RabbitMQ, если нужно
        location /minio/ {
            proxy_pass http://minio:9000/;
        }

        location /rabbitmq/ {
            proxy_pass http://rabbitmq:15672/;
        }
    }
}