// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Renk72Lk.DataAccess.Contexts;

#nullable disable

namespace Renk72Lk.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("aspnet_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnet_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("aspnet_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("aspnet_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnet_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnet_user_tokens", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Build")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("House")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Index")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Office")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.AttachmentFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("attachment_files", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.AttachmentsPointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("Power")
                        .HasColumnType("float");

                    b.Property<int?>("TechnicalSpecificationsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("Voltage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalSpecificationsId");

                    b.ToTable("attachments_points", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.AttachmentsStageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CommissioningPeriod")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DesignPeriod")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("Power")
                        .HasColumnType("float");

                    b.Property<int?>("TechnicalSpecificationsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalSpecificationsId");

                    b.ToTable("attachments_stages", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.AuthHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LoginIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("auth_history", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidAttachmentsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BenefitFileId")
                        .HasColumnType("int");

                    b.Property<int?>("BidId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IsAgreePreviewPDF")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int?>("OtherFileId")
                        .HasColumnType("int");

                    b.Property<int?>("PassportFileId")
                        .HasColumnType("int");

                    b.Property<int?>("PowerDevicesPlanFileId")
                        .HasColumnType("int");

                    b.Property<int?>("SnilsFileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BenefitFileId");

                    b.HasIndex("BidId")
                        .IsUnique();

                    b.HasIndex("OtherFileId");

                    b.HasIndex("PassportFileId");

                    b.HasIndex("PowerDevicesPlanFileId");

                    b.HasIndex("SnilsFileId");

                    b.HasIndex("UserId");

                    b.ToTable("bids_attachments", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidConnectionObjectInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressOfObject")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("BidId")
                        .HasColumnType("int");

                    b.Property<string>("CadastralNumber")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ConnectionType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GuarantySupplier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ObjectName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PowerDevice")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReasonForBid")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TypeOfContract")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VoltageClass")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BidId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("bids_connection_object_info", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DocumentFileId")
                        .HasColumnType("int");

                    b.Property<int?>("IsArchive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Service")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TicketStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentFileId");

                    b.HasIndex("UserId");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidPersonalInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ActualAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("BidId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IsAgreePersonData")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PassportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PassportIssuedBy")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PassportSeries")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PassportType")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("RegistrationAddressId")
                        .HasColumnType("int");

                    b.Property<string>("Snils")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActualAddressId");

                    b.HasIndex("BidId")
                        .IsUnique();

                    b.HasIndex("RegistrationAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("bids_personal_info", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidRepresentativeInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Attorney")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("BidId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PassportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PassportIssuedBy")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PassportSeries")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PassportType")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BidId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("bids_representative_info", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidTechnicalSpecificationsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BidId")
                        .HasColumnType("int");

                    b.Property<int?>("CountOfGenerators")
                        .HasColumnType("int");

                    b.Property<int?>("CountOfTransformers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("GeneratorsPower")
                        .HasColumnType("float");

                    b.Property<string>("JustificationTechMin")
                        .HasColumnType("longtext");

                    b.Property<string>("NatureLoad")
                        .HasColumnType("longtext");

                    b.Property<float?>("OldPointPower")
                        .HasColumnType("float");

                    b.Property<float?>("OldPointVolt")
                        .HasColumnType("float");

                    b.Property<string>("PaymentOrder")
                        .HasColumnType("longtext");

                    b.Property<string>("ReliabilityCategory")
                        .HasColumnType("longtext");

                    b.Property<float?>("TechMin")
                        .HasColumnType("float");

                    b.Property<float?>("TransformersPower")
                        .HasColumnType("float");

                    b.Property<string>("TypeOfLoad")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BidId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("bids_technical_specifications", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BidId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BidId");

                    b.HasIndex("FileId");

                    b.HasIndex("UserId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ActualAddressId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("PassportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PassportIssuedBy")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PassportSeries")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PassportType")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("RegistrationAddressId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Snils")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserDataAgreementFileId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActualAddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("RegistrationAddressId");

                    b.HasIndex("UserDataAgreementFileId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.AttachmentsPointEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.BidTechnicalSpecificationsEntity", "TechnicalSpecifications")
                        .WithMany("Points")
                        .HasForeignKey("TechnicalSpecificationsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TechnicalSpecifications");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.AttachmentsStageEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.BidTechnicalSpecificationsEntity", "TechnicalSpecifications")
                        .WithMany("Stages")
                        .HasForeignKey("TechnicalSpecificationsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TechnicalSpecifications");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.AuthHistoryEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", "User")
                        .WithMany("AuthHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidAttachmentsEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.AttachmentFileEntity", "BenefitFile")
                        .WithMany()
                        .HasForeignKey("BenefitFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.BidEntity", "Bid")
                        .WithOne("Step5")
                        .HasForeignKey("Renk72Lk.DataAccess.Entities.BidAttachmentsEntity", "BidId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Renk72Lk.DataAccess.Entities.AttachmentFileEntity", "OtherFile")
                        .WithMany()
                        .HasForeignKey("OtherFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.AttachmentFileEntity", "PassportFile")
                        .WithMany()
                        .HasForeignKey("PassportFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.AttachmentFileEntity", "PowerDevicesPlanFile")
                        .WithMany()
                        .HasForeignKey("PowerDevicesPlanFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.AttachmentFileEntity", "SnilsFile")
                        .WithMany()
                        .HasForeignKey("SnilsFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", "User")
                        .WithMany("Attachments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BenefitFile");

                    b.Navigation("Bid");

                    b.Navigation("OtherFile");

                    b.Navigation("PassportFile");

                    b.Navigation("PowerDevicesPlanFile");

                    b.Navigation("SnilsFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidConnectionObjectInfoEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.BidEntity", "Bid")
                        .WithOne("Step3")
                        .HasForeignKey("Renk72Lk.DataAccess.Entities.BidConnectionObjectInfoEntity", "BidId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", "User")
                        .WithMany("ConnectionObjectInfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.AttachmentFileEntity", "DocumentFile")
                        .WithMany()
                        .HasForeignKey("DocumentFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DocumentFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidPersonalInfoEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.AddressEntity", "ActualAddress")
                        .WithMany()
                        .HasForeignKey("ActualAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.BidEntity", "Bid")
                        .WithOne("Step1")
                        .HasForeignKey("Renk72Lk.DataAccess.Entities.BidPersonalInfoEntity", "BidId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Renk72Lk.DataAccess.Entities.AddressEntity", "RegistrationAddress")
                        .WithMany()
                        .HasForeignKey("RegistrationAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", "User")
                        .WithMany("PersonalInfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ActualAddress");

                    b.Navigation("Bid");

                    b.Navigation("RegistrationAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidRepresentativeInfoEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.BidEntity", "Bid")
                        .WithOne("Step2")
                        .HasForeignKey("Renk72Lk.DataAccess.Entities.BidRepresentativeInfoEntity", "BidId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", "User")
                        .WithMany("RepresentativeInfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidTechnicalSpecificationsEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.BidEntity", "Bid")
                        .WithOne("Step4")
                        .HasForeignKey("Renk72Lk.DataAccess.Entities.BidTechnicalSpecificationsEntity", "BidId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", "User")
                        .WithMany("TechnicalSpecifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.MessageEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.BidEntity", "Bid")
                        .WithMany("Messages")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Renk72Lk.DataAccess.Entities.AttachmentFileEntity", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.UserEntity", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bid");

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.UserEntity", b =>
                {
                    b.HasOne("Renk72Lk.DataAccess.Entities.AddressEntity", "ActualAddress")
                        .WithMany()
                        .HasForeignKey("ActualAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.AddressEntity", "RegistrationAddress")
                        .WithMany()
                        .HasForeignKey("RegistrationAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Renk72Lk.DataAccess.Entities.AttachmentFileEntity", "UserDataAgreementFile")
                        .WithMany()
                        .HasForeignKey("UserDataAgreementFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActualAddress");

                    b.Navigation("RegistrationAddress");

                    b.Navigation("UserDataAgreementFile");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidEntity", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Step1");

                    b.Navigation("Step2");

                    b.Navigation("Step3");

                    b.Navigation("Step4");

                    b.Navigation("Step5");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.BidTechnicalSpecificationsEntity", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Renk72Lk.DataAccess.Entities.UserEntity", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("AuthHistory");

                    b.Navigation("Bids");

                    b.Navigation("ConnectionObjectInfos");

                    b.Navigation("Messages");

                    b.Navigation("PersonalInfos");

                    b.Navigation("RepresentativeInfos");

                    b.Navigation("TechnicalSpecifications");
                });
#pragma warning restore 612, 618
        }
    }
}
